### ISSUE TITLE
effect type cannot be null

### ISSUE THREAD

**Issue by jasca** [Guillefreak/ArgentinasDelight#5]
Master ante todo gran trabajo, Cuando logre poder tomarme un mate se crashea todo y nunca mas podes ingresar al servidor.
Estaba usando ArchLigth 1.20.1 te copio lo que pude recuperar del log.
Saludos!

288734at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}
Caused by: java.lang.IllegalArgumentException: effect type cannot be null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar%23108!/:?] {re:mixin}
	at org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:52) ~[arclight-1.20.1-1.0.2-730181a4.jar%23168!/:arclight-1.20.1-1.0.2-730181a4] {re:mixin,re:classloading}
	at org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:72) ~[arclight-1.20.1-1.0.2-730181a4.jar%23168!/:arclight-1.20.1-1.0.2-730181a4] {re:mixin,re:classloading}
	at org.bukkit.craftbukkit.v1_20_R1.potion.CraftPotionUtil.toBukkit(CraftPotionUtilMixin.java:113) ~[arclight-1.20.1-1.0.2-730181a4.jar%23168!/:arclight-1.20.1-1.0.2-730181a4] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftPotionUtilMixin,pl:mixin:A}
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityPotionEffectChangeEvent(CraftEventFactoryMixin.java:1668) ~[arclight-1.20.1-1.0.2-730181a4.jar%23168!/:arclight-1.20.1-1.0.2-730181a4] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftEventFactoryMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityPotionEffectChangeEvent(CraftEventFactoryMixin.java:1663) ~[arclight-1.20.1-1.0.2-730181a4.jar%23168!/:arclight-1.20.1-1.0.2-730181a4] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftEventFactoryMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
	at net.minecraft.world.entity.LivingEntity.m_147207_(LivingEntityMixin.java:3883) ~[server-1.20.1-20230612.114412-srg.jar%23175!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:arclight_implementer:async,pl:arclight_implementer:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:activationrange.entity.LivingEntityMixin_ActivationRange,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin$ApotheosisCompatMixin,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin$ObscureApiCompat,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A}
	at net.minecraft.world.entity.LivingEntity.m_7292_(LivingEntityMixin.java:921) ~[server-1.20.1-20230612.114412-srg.jar%23175!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:arclight_implementer:async,pl:arclight_implementer:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:activationrange.entity.LivingEntityMixin_ActivationRange,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin$ApotheosisCompatMixin,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin$ObscureApiCompat,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A}
	at net.mcreator.unoveinte.procedures.TranquilidadOnEffectActiveTickProcedure.execute(TranquilidadOnEffectActiveTickProcedure.java:23) ~[Argentina's+Delight+1.20.1+(ver1.21).jar%23169!/:?] {re:classloading}
	at net.mcreator.unoveinte.potion.TranquilidadMobEffect.m_6742_(TranquilidadMobEffect.java:22) ~[Argentina's+Delight+1.20.1+(ver1.21).jar%23169!/:?] {re:classloading}
	at net.minecraft.world.effect.MobEffectInstance.m_19550_(MobEffectInstance.java:204) ~[server-1.20.1-20230612.114412-srg.jar%23175!/:?] {re:mixin,xf:fml:forge:potion,re:classloading,xf:fml:forge:potion}
	at net.minecraft.world.effect.MobEffectInstance.m_19552_(MobEffectInstance.java:171) ~[server-1.20.1-20230612.114412-srg.jar%23175!/:?] {re:mixin,xf:fml:forge:potion,re:classloading,xf:fml:forge:potion}
	at net.minecraft.world.entity.LivingEntity.m_21217_(LivingEntityMixin.java:3797) ~[server-1.20.1-20230612.114412-srg.jar%23175!/:?]

**Comment by Guillefreak** [comment]
recordas que mate especifico tomaste?El 21 ene. 2024 18:25, Jasca ***@***.***> escribió:
Master ante todo gran trabajo, Cuando logre poder tomarme un mate se crashea todo y nunca mas podes ingresar al servidor.
Estaba usando ArchLigth 1.20.1 te copio lo que pude recuperar del log.
Saludos!
288734at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}
Caused by: java.lang.IllegalArgumentException: effect type cannot be null
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar%23108!/:?] {re:mixin}
at org.bukkit.potion.PotionEffect.(PotionEffect.java:52) ~[arclight-1.20.1-1.0.2-730181a4.jar%23168!/:arclight-1.20.1-1.0.2-730181a4] {re:mixin,re:classloading}
at org.bukkit.potion.PotionEffect.(PotionEffect.java:72) ~[arclight-1.20.1-1.0.2-730181a4.jar%23168!/:arclight-1.20.1-1.0.2-730181a4] {re:mixin,re:classloading}
at org.bukkit.craftbukkit.v1_20_R1.potion.CraftPotionUtil.toBukkit(CraftPotionUtilMixin.java:113) ~[arclight-1.20.1-1.0.2-730181a4.jar%23168!/:arclight-1.20.1-1.0.2-730181a4] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftPotionUtilMixin,pl:mixin:A}
at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityPotionEffectChangeEvent(CraftEventFactoryMixin.java:1668) ~[arclight-1.20.1-1.0.2-730181a4.jar%23168!/:arclight-1.20.1-1.0.2-730181a4] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftEventFactoryMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityPotionEffectChangeEvent(CraftEventFactoryMixin.java:1663) ~[arclight-1.20.1-1.0.2-730181a4.jar%23168!/:arclight-1.20.1-1.0.2-730181a4] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftEventFactoryMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
at net.minecraft.world.entity.LivingEntity.m_147207_(LivingEntityMixin.java:3883) ~[server-1.20.1-20230612.114412-srg.jar%23175!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:arclight_implementer:async,pl:arclight_implementer:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:activationrange.entity.LivingEntityMixin_ActivationRange,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin$ApotheosisCompatMixin,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin$ObscureApiCompat,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A}
at net.minecraft.world.entity.LivingEntity.m_7292_(LivingEntityMixin.java:921) ~[server-1.20.1-20230612.114412-srg.jar%23175!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:arclight_implementer:async,pl:arclight_implementer:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:activationrange.entity.LivingEntityMixin_ActivationRange,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin$ApotheosisCompatMixin,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin$ObscureApiCompat,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A}
at net.mcreator.unoveinte.procedures.TranquilidadOnEffectActiveTickProcedure.execute(TranquilidadOnEffectActiveTickProcedure.java:23) ~[Argentina's+Delight+1.20.1+(ver1.21).jar%23169!/:?] {re:classloading}
at net.mcreator.unoveinte.potion.TranquilidadMobEffect.m_6742_(TranquilidadMobEffect.java:22) ~[Argentina's+Delight+1.20.1+(ver1.21).jar%23169!/:?] {re:classloading}
at net.minecraft.world.effect.MobEffectInstance.m_19550_(MobEffectInstance.java:204) ~[server-1.20.1-20230612.114412-srg.jar%23175!/:?] {re:mixin,xf:fml:forge:potion,re:classloading,xf:fml:forge:potion}
at net.minecraft.world.effect.MobEffectInstance.m_19552_(MobEffectInstance.java:171) ~[server-1.20.1-20230612.114412-srg.jar%23175!/:?] {re:mixin,xf:fml:forge:potion,re:classloading,xf:fml:forge:potion}
at net.minecraft.world.entity.LivingEntity.m_21217_(LivingEntityMixin.java:3797) ~[server-1.20.1-20230612.114412-srg.jar%23175!/:?]
